### ISSUE TITLE
ThankYouForPurchaseForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#20]
Shows a "Thanks for ordering XXX" screen.
XXX can be of different things.  Details will be provided by parent as props
This is not really a form as there's nothing for user to submit.  But structure wise it's at form level, i.e. using components and have info to show.

## URL
./src/form/ThankYouForPurchaseForm.js

## Props List

One of the following must be present.
- [x] `order_id`: String
- [x] `orderType`: String

## Spec

- [x] If none of the props is available, load `SystemError` component #22 , supply `message` saying invalid sales order number.

- [x] Create a page say thanks for purchase.  In 10 seconds, redirect to `/dash`.  Show `You will be redirected to Dashboard in 10 seconds`.  Update the amount of seconds left every second.

**Comment by screw123** [comment]
@omiq17 
Hi Rakib,

this one is also for you.  Thanks for help!

Ross

**Comment by omiq17** [comment]
Thanks for assigning me new components. I will check, work on them and let you know.

**Comment by omiq17** [comment]
Opened a new branch named `thanks` for this. You can check the work on [testpage](http://localhost:3000/testPage)

Let me know if it is okay or not.
