### ISSUE TITLE
AccountListForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#26]
Obtain account list from existing state, and at the same time fetch from backend for further info.
Once data from backend is available, update children with new data by giving out new props.

Main objective: to show a brief summary of each account, and allow user to interact.
Interact means search from lists of account (implement later), view/edit each account, activate/disable each account (implement later)
This is not really a form, as nothing for user to submit (except search).  We name it as a form just to follow the app structure

## URL
./src/form/AccountListForm.js

## Spec

- [x] On load, get accounts from #24 `GqlApi.state.myself` and show on screen.  Should combine all accounts from `myself.accountOwn_id`, `myself.accountManage_id`, `myself.accountView_id`

- [x] AccountListForm contains a search component and 3 lists implementing `InfoList` #27 . `accountOwn`, `accountManage` and `accountView` will be 3 lists.

- [x] Create a styled component that accepts `props.data`, generate `name`, `accountType`, and `balance` from each account respectively.  If `balance` is undefined (in case of accountView), render a blank `balance` element instead.

- [x] provide`AccountLine` (see below sub-component) as `renderComponent` to `InfoList` 

# AccountLine (sub-component)

AccountLine is going to provide as props to `InfoList` 
## Props List
data: receive from `InfoList`.  It should contains a single Account object containing `{_id, name, accountType, balance, isActive, accessRight}`

## Spec

- [x] Create a styled component for `_id`, `name`, `accountType`, `balance`, `isActive`, give each component some reasonable basic CSS

- [x] just display everything to front-end

- [x] The wraping div should also be a styled-component to increase flexibility of look and feel design later.

- [x] On right hand side of the line, _show "Edit" icon, "View" icon, "Close" icon.  If accessRight=='Own', show all 3 icons, otherwise only show `View`.  Icon should use `ListIcon` in `./src/component/InfoList.js`

## TBC

- If list of account > 10, enable search
- If (1) accountType is 'BUSINESS', (2) currentUser is owner, (3) account contains no active boxes, allow to disable account _also think about how personal users can disable accounts_
- _edit button, details button_

# AccountBoxCount (sub-component)
Receive the account object from AccountLine, show how many boxes there are currently under this account.
Spec has not been figured out, act as a placeholder for now.

## Props
data: provided by AccountLine

## Spec

- [x] Just show "Box Info Loading...(pending to develop)" for now

## TBC
- Pending for backend to develop query [`getAccountListWithInfo`](https://github.com/screw123/p001/issues/14)
- To confirm which icon to use for each type of boxes

**Comment by screw123** [comment]
@omiq17 

Please take the following as sample data supplied to `AccountListForm`

```
[ {"_id":"5b518c4c031c7d0179e23b6a","accountType":"PERSONAL","owner_id":"5b518c4b031c7d0179e23b69","name":"DEFAULT","isActive":true,"creationDateTime":"2018-07-20T07:16:28.117Z","updateDateTime":"2018-07-20T07:16:28.117Z","balance":500.45,"priceList":"VIP","address_id":["5afba4f4b2d52237e3f2fc75","5afba4fbb2d52237e3f2fc76"],"defaultBillingAddress_id":"5afba4f4b2d52237e3f2fc75","defaultShippingAddress_id":"5afba4fbb2d52237e3f2fc76"},
{"_id":"5b8769d78b53fbb204118e8b","accountType":"PERSONAL","owner_id":"5b518c4b031c7d0179e23b69","name":"Testing","isActive":true,"creationDateTime":"2018-07-20T07:16:28.117Z","updateDateTime":"2018-07-20T07:16:28.117Z","balance":0,"priceList":"DEFAULT"}
]
```

**Comment by screw123** [comment]
@omiq17 you can leave the GqlApi bebind, because that involved calling backend and get data, which I will handle.

Please just focus on getting the module work.  You can try call `AccountListForm` from testPage, and supply the set of data above as props.  Remaining I will handle.

**Comment by omiq17** [comment]
Worked with specs. Haven't figured out TBC properly now. I will check work with TBC some times later.

I used ApolloProvider, GqlApiSubscriber as a hint from `form/UserProfileForm.js`. Not sure about this :grimacing: 

I haven't checked with `testPage`. I think you can write the code for getting data from `backend` here and check and then let me know the corrections.
