### ISSUE TITLE
InfoList

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#27]
A list component implementing [`react-virtualized`](https://github.com/bvaughn/react-virtualized)

## URL
./src/component/InfoList.js

## Props List

- [x] data: an array with all data

- [x] headerText: String

- [x] headerIconLeft: React components.  Show at left hand side of headerText

- [x] headerIconRight: React components.  Show at right hand side of headerText

- [x] listComponent: optional.  If this prop is provided, must be a React Component that accepts `({index, isScrolling, isVisible, key, parent, style})`

## Spec

- [x ] headerText use `SectionHeader` in `./src/component/Background.js`, and show `props.headerIconLeft`, `props.headerText`, `props.headerIconRight` respectively

- [x] for each item in `props.data`, render with `props.listComponent`.  If no `listComponent supplied, use `DefaultListItem` (sub-component in this file.  see below).

## TBC
- buttonList: for specifying a list of buttons to add to bottom of list

# DefaultListComponent
This is the default List Item that use with `InfoList`
## URL
./src/form/InfoList.js

## Props List
`data`: the whole set of data in array
`a`: `a = {index, isScrolling, isVisible, key, parent, style}`

## Spec

- [x] For each key/value pair in `props.data`, show as `key: value`

**Comment by omiq17** [comment]
Isn't the URL of **ListItem** will be  `./src/form/ListItem.js`?

**Comment by screw123** [comment]
Since ListItem will only be used by InfoList, I suggest to put into same file.

**Comment by omiq17** [comment]
Initially added `./src/component/InfoList.js` , `./src/form/InfoList.js`  and implement `react-tiny-virtual-list`.
Please check those.

But these are not functionally tested. I request you to provide a demo Props List object for InfoList component so that I can test it from `testpage`.

**Comment by omiq17** [comment]
At first, as I got this error:  `Module build failed: Duplicate declaration "InfoList"`
So, I changed the file name `./src/form/InfoList.js` to `./src/form/ListItem.js`

Checking functionality is the real part :face_with_head_bandage: 
Check `/testPage` and let me know the corrections.

**Comment by omiq17** [comment]
No problem... Take your time.
I am trying issue #26.

**Comment by screw123** [comment]
@omiq17 I now saw how it's not implemented right.
`InfoList` should be a single list that helps to generate a lot of items.
```
<Header>
<VirtualList>
  <item1>
  <item2>...
</VirtualList>
```
Now it's many small VirtualLists, and every list contains only 1 item.

**Comment by screw123** [comment]
This is now done.

**Comment by screw123** [comment]
@omiq17 This component is now done.  I make it to use `react-virtualized` instead.
