### ISSUE TITLE
EditAddressForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#34]
Very Similar to UserProfileForm, but this time let user edit address instead.
You may refer to `AddNewAddressForm.js` in str_branch currently.

## URL
`./src/form/EditAddressForm.js`

## Props
`address`: A complete address  object from backend, which can look like this:
```{
  "_id":"5ba0b52cec46627f7930b9ba",
  "legalName":"My Office",
  "addressCountry":"Hong Kong",
  "streetAddress":"Flat B2, 3/F, Ching Cheong Ind. Bldg., 1 Kwai Cheong Rd,",
  "addressRegion1":"So Kwun Wat"
  "addressRegion2":"屯門"
  "telephone":"99911122",
  "account_id":"5b518c4c031c7d0179e23b6a",
  "isActive":true,
  "addressType":"CUSTOMER",
  "creationDateTime":"2018-09-18T08:19:56.673Z",
  "updateDateTime":"2018-09-18T08:19:56.673Z"
}
```

## Spec

This form need to show following fields, in order: 

- [x] `legalName`: String, cannot be empty

- [x] `streetAddress`: String, min 5 chars, max 500, cannot be empty

- [x] `addressRegion1`: String, cannot be empty

- [x] `addressRegion2`: String, cannot be empty

- [x] `addressCountry`: String, cannot be empty

- [x] `telephone`: String, contains 8 numbers

- [ ] `isActive`: Boolean.  In Formik it's name is `disable`, and value is reverse of isActive, i.e. `isActive === !disable`.  

- [ ] When submit, submit the 7 fields above, together with `_id`

- [ ] submit to `updateAddress` in './src/query/query.js`

**Comment by omiq17** [comment]
Checked with your given `address` object from `testpage.js`. 

Took the code from `AddNewAddressForm.js` and then modified with respect to given specs. Got a bug in 
function `validate(v)` at line 33. Then I fixed it. Check how current `validate(v)` differs from `AddNewAddressForm.js` and you can fix it there too. 

Added a demo `updateAddress` in `query.js`. You can fix it.

Modified the design of `Submit` button a bit. You can check line no. 59-60 of `./src/component/Formik-Basic.js`. 

In **TBC**:
- `addressCountry` is already using `MultiSelect`
-  Added `MutiSelect` to `addressRegion2` by almost copying `addressCountry`. Please check this.

I have checked the Frontend. Please check the Backend @screw123 .
