### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#36]
A Gallary component that made from [react-virtualized](https://github.com/bvaughn/react-virtualized).
Make use of `Grid` to show all images in a square format

## URL
'./src/component/Gallary.js'

## Props

- [x] `headerText`: String (optional).  Show as header on top of Gallery if provided.

- [x] `headerIconLeft`: React Component (optional).  Show at left hand side of headerText if provided.

- [x] `headerIconRight`: React Component (optional).  Show at right hand side of headerText if provided.

- [x] `data`: Array of objects, contains all data that need to show from parent

- [x] `keyForThumbnailURL`: String. The key in the object that contains the URL for thumbnail.  e.g. data[0]={_id, name, URL, URL_thumbnail}, then `keyForThumbnailURL` will equals to `URL_thumbnail`

- [ ] `imageComponent`: React Component(optional).  Use this to provide to `cellRenderer` prop of `Grid`

- [x] `imageSize`: Integer (optional).  Size of a cell in grid.  We will render square cells, so this is for both height and width of a cell

- [x] **NEW `selectMode`: Boolean.  Default is false.  If it's true, clicking on image will become selecting the image instead.**

- [x] **NEW `onSelect`: Function.  if selectMode is true, selecting/de-selecting will trigger this function instead of showing Modal.**

- [x] **NEW `selectedValue`: Array of object.  Only required if `selectMode` is true.  Contains all selected items in data.**

## Spec

- [x] Refer to Info List #27, Put in Section Header, and place head icon left/right and header text inside.

- [x] **NEW Below Section Header, add a div to show icons when they are provided as props by parent**

- [x] If headerText, header icon left/right are not provided, do not render the component (use {[checkcase] && [React component]} technique is fine)

- [x] Refer to [Grid Doc](https://github.com/bvaughn/react-virtualized/blob/master/docs/Grid.md), construct a grid

- [x] **NEW if `props.selectMode` is true, the onclick method to `DefaultCellRenderer` will select the cell.  Else onclick will show a `Modal` (./src/component/Modal.js), inside the Modal, will show fill size image. **

## TBC

- add select icon on demand
- onSelect: callback that when items in the grid is selected
- buttonList: array of objects that can let gallery generate buttons

# DefaultCellRenderer

This is the default cell renderer in case props.imageComponent is not provided in `Gallery` component.

## Props

- [x] data: Object.  A single object in the data array.  Do not pass the whole array

- [x] key: String. the key of this item.  This is needed by React

- [x] imageSize: Integer.  width & height of the image rendered.

- [ ] `keyForThumbnailURL`: String. The key in the object that contains the URL for thumbnail.  e.g. data[0]={_id, name, URL, URL_thumbnail}, then `keyForThumbnailURL` will equals to `URL_thumbnail`

- [x] `onClick`: Function. The function that triggered when the component is clicked.

## Spec

- [x] Show the thumbnail.  This means get the URL from `data`, extract the URL from `keyForThumbnailURL`, and show it using `<img src=`

- [x] image size is in `props.imageSize`

- [x] wrap the `img` tag with a `span`

## TBC

**Comment by screw123** [comment]
List of pictures as sample for your dev:
Pass this from testPage to this component.

["http://lorempicsum.com/nemo/355/200/1",
"http://lorempicsum.com/nemo/355/200/2",
"http://lorempicsum.com/nemo/200/200/3",
"http://lorempicsum.com/nemo/250/200/4",
"http://lorempicsum.com/nemo/280/200/5",
"http://lorempicsum.com/nemo/355/200/6",
"http://lorempicsum.com/nemo/300/200/7",
"http://lorempicsum.com/nemo/150/200/8",
"http://lorempicsum.com/nemo/250/200/9"]

**Comment by screw123** [comment]
@omiq17 as said earlier this is a new component for you.  Currently it's only 50% of spec as I don't have time to figure it out.
Please start working on it first.  We will enrich the spec later on and you can also add code later.

**Comment by omiq17** [comment]
some inquiries

**Comment by omiq17** [comment]
`react-virtualized` seems great to work.

I have some inquiries:
- Will we show the image thumbnails only? or will I show image name, id, thumbnail?
- It we show only the image thumbnails, will we show them horizontally, side by side?

**Comment by omiq17** [comment]
One more thing:

Will we create separate component for SectionHeader as it is used both by InfoList and Gallery?

**Comment by screw123** [comment]
@omiq17 


 

>    Will we show the image thumbnails only? or will I show image name, id, thumbnail?

This is now just version 1.  We will add more requirements soon.  For now please just finish this version 1.

>    It we show only the image thumbnails, will we show them horizontally, side by side?
You should be using `Grid`, which should be side by side by default
>    When click on an image, will we implement Modal to show the original sized image? or will we follow other option?
Will be added later on.
> Will we create separate component for SectionHeader as it is used both by InfoList and Gallery?
Good suggestion.  Let me write it up.  For now you just copy code from InfoList.

**Comment by screw123** [comment]
@omiq17 I checked the code, in general they worked.
However for the layout I want something like [this](https://www.p30template.com/images/thumb/vinaarticlegridgallery/slide/vinaarticlegridgallery-full-view2.jpg)

Please help to hardcode it to 3 columns for now.

Other requirements I will hopefully update within next few hours.

**Comment by omiq17** [comment]
Ok...  I will try to divide it into 3 columns.

**Comment by screw123** [comment]
Added new spec.

This time we enhance the component.
1. Allow clicking on thumbnails.  When click on thuumbnail, show a fullscreen modal that show the full size picture.
2. Allow enabling "Select Mode".  In select mode, clicking on thumbnail will not show full size picture, but overlay a tick.  Parent provide a `onSelect` function to Gallery, Gallery provide this function to `DefaultCellRenderer` or `ImageComponent`.  State is managed by parent.
3. Parent should maintain a `selectedItem` array, and provide to `Gallery`.

**Comment by omiq17** [comment]
Okay... 
Looks a bit challenging. I will try and let you know if I got any problem.

**Comment by omiq17** [comment]
`react-virtualized` seems little inflexible to me. 
Currently, I have made a 3 columns gallery using `Flexbox` grid system. Let me know if it is okay to you or not. Also you can give me corrections on it. 
After we finalize this gallery design, I will work on NEW issues.

**Comment by screw123** [comment]
@omiq17 Flexbox may not be the best way to do:
1. With Flexbox, pictures is not generated at the fixed position on the page, but rather the position will jump as more and more pictures being loaded.  E.g. On a slow connection, when picture loading sequence becomes 6 1 2 4 5 3, picture 6's position will keep going right/down, when user want to click on picture 6, they will become keep clicking on something else.

2. When we have more pictures, e.g. 100+, it will consume a lot of bandwidth.  React-virtualized's dynamic loading can help on this by only load what is shown on screen first.

Anyway, the issue with React-virtualized I can try to solve myself.  Please go ahead to make sure other new specs are coded.  Thanks!

**Comment by omiq17** [comment]
Finally got the flexibility on `react-virtualized`
Made the 3 columns Gallery. Check and let me know.

**Comment by screw123** [comment]
@omiq17 looks fine so far.

Please kindly check the new spec and code accordingly.  I highlight them below:

1.     Allow clicking on thumbnails. When click on thuumbnail, show a fullscreen modal that show the full size picture.
2.     Allow enabling "Select Mode". In select mode, clicking on thumbnail will not show full size picture, but overlay a tick. Parent provide a onSelect function to Gallery, Gallery provide this function to DefaultCellRenderer or ImageComponent. State is managed by parent.
3.     Parent should maintain a selectedItem array, and provide to Gallery.
4.     (Optional at this stage) Selected items will show overlay. For overlay you can refer to here https://www.w3schools.com/howto/howto_css_image_overlay_icon.asp

**Comment by omiq17** [comment]
Yes. I haven't implemented this features. Wanted to sure if the gallery design is right. Thanks for your confirmation. 
I will implement these clicking features and let you know.

**Comment by omiq17** [comment]
- I have created a new page `GalleryPage.js`  for this Gallery, routes it and gave a `menuName` of `Gallery`. So, now you can check the result by in clicking Gallery on navbar.
- Moved all the styles to `GalleryStyles.js`
- I made a small mistake :neutral_face: I haven't checked your `Modal.js` component. Instead I have made a Modal myself. Check that Modal. However, if you want to repalce that and use your Modal, then let me know. I will implement this. I am sorry for this.
- Check the Overlay by making the `selectMode: true,` in `GalleryPage.js`. Here, I use Font Awesome icon and for this I used their cdn in `index.html`

Feel free to give the corrections.

**Comment by screw123** [comment]
@omiq17 Thanks, I made a small change on handleImageClick.  Other than that the component is mostly functional as specified.  Thanks!  I will merge it to master.
