### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#41]
Navbar of the app

## URL
'.src/component/Navbar.js'

## Props
`routes`: Array.  Within this array, it should contain objects with following structure:

- [x] `path`: String e.g. '/login'.  Pass to router to match URL.

- [x] `linkURL`: String. If it's different from `path`, e.g. if path is `/quotation/:quote_id?`, linkURL can be `/quotation` so variables won't be affecting the link

- [x] `menuName`: String.  Show in Navbar
- [x] `component`: React Component to load when URL matched
- [x] `navbar.showBeforeLogin`: Boolean.  If true, show even user is not logined.
- [x] `navbar.showAfterLogin`: Boolean.  If true, show after user is logined.

- [x] `navbar.firstLevel`: Boolean.  If true, and `component` is defined, all children will be ignored.  If true and `component` is undefined, then clicking it will show a menu that shows all 2nd level items.

- [x] `navbar.itemID`: Integer.  This has 2 uses: (1) To use as rank.  Smaller number will put it towards LHS/top. (2) As an ID that use to match 2nd level items under this.

- [x] `navbar.parentID` Integer.  Only useful for 2nd level items.  Specify the `firstLevelID` of items that it should fall under.

- [x] `router.requireLogin`: Boolean.  If true, user will be redirected to login page if not logined.

## TBC

**Comment by screw123** [comment]
Specs all implemented.

**Comment by screw123** [comment]
@omiq17 The NavBar is now mostly in place for desktop, but when visit via mobile phone, we will need a more compact presentation.  Do you have any suggestion?

**Comment by omiq17** [comment]
Responsive design has been a trending and important topic in web design as the mobile users are growing rapidly.
I always try to ensure responsive design while making a website. Some days ago, We made the website for our company (where I do job) which you can check here: [BigGo](https://biggo.com.bd/) 
In that project we follow this CSS responsive design standard:

**Comment by omiq17** [comment]
Responsive design has been a trending and important topic in web design as the mobile users are growing rapidly.I always try to ensure responsive design while making a website. Some days ago, We made the website for our company (where I do job) which you can check here: BigGo 
In that project we follow this CSS responsive design standard:

**Comment by screw123** [comment]
The "from_codepen2" is similar to what I want to implement.  I used some existing packages and their performance are bad once the Menu gets big.  So I want to code one ourselves.

You can see I already implemented the "desktop version" of NavBar.  Please try to add the "from_codepen2" once screen width is below, say, 640px.  We can fine tune later on from there.
@omiq17

**Comment by omiq17** [comment]
Hi Ross, 
It was a challenging and an interesting task. You coded well for desktop version. 

- At first, I moved the CSS design to `NavbarSyles.js` to keep the styles separated.

**Comment by omiq17** [comment]
Hi Ross, 
It was a challenging and an interesting task. You coded well for desktop version. Here is my steps for making the mobile version menu:

- At first, I moved the CSS design to `NavbarSyles.js` to keep the styles separated. 
- Added a state `showMenuBar` and add a handle function for this state which is `toggleMenuBar()` in `LocalApi.js`
-  Added `MobileMenuBar` which contains the menu for mobile screens. It kept hide when `showMenuBar` is false.
- Also added transition property.

Check on `navbar` branch and let me know your thoughts. Thanks!

**Comment by screw123** [comment]
@omiq17 Looks quick and close to perfect!  I quickly merged it into master, I can see some minor issues but we can deal with it later.  Thanks!
