### ISSUE TITLE
StripeComponents (StripeCardNumberInput, StripeCardExpiryInput, StripeCardCVCInput)

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#52]
A set of component that style the related components from [React-Stripe-Element](https://github.com/stripe/react-stripe-elements)

## URL
./src/component/StripeComponents.js

## Spec
There's some catch in the structure that makes of Stripe elements, that makes it not immediately accept styles from styled-component.  As a start please find a way to style the components exactly like text inputs in './src/components/Formik-TextInput.js'.

A branch 'StripeComponents' is created for this, please try to continue my work on that branch, thanks.

These components are imported into `./src/form/PaymentInfoForm.js`.  To test, you just need to render PaymentInfoForm somewhere.

**Comment by omiq17** [comment]
At first, I thought I need to understand `React-Stripe-Element` to do this. Then I released I just need to copy the design of Formik Form. 

I created a `route` of `/stripe`. So you can check the component here: [http://localhost:3000/stripe](http://localhost:3000/stripe)

Let me know if I understand the issue and the corrections I need to do.

**Comment by screw123** [comment]
Works fine, thanks!
I changed PaymentInfoForm.js into AddCreditCardForm.js
