### ISSUE TITLE
ToolTip

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#57]
@omiq17 
Please fix './src/component/ToolTip.js

I just randomly copy some existing code from online, ultimately I need a working ToolTip component to use as a basic with others.

Please kindly try to fix the CSS of `ToolTipBox` and `ToolTipText` so the tooltip will properly show, thanks!

**Comment by screw123** [comment]
Codes I'm referring to:
https://www.w3schools.com/css/css_tooltip.asp

**Comment by omiq17** [comment]
You had already code it well. There was a little mistake on hover. I fixed it.
You can check it in `tooltip` branch at [testpage](http://localhost:3000/testPage)
