### ISSUE TITLE
RemoveCreditCardForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#60]
Please create a component in `../form/RemoveCreditCardForm.js`

You can copy and modify from `../form/AddCreditCardForm.js`

Props supplied:
`source`: A credit card object, pls refer to comment below for a sample
`account_id`: A string
`onRemoveSuccess`: A function that you will call after mutation is successful
`cancelRemoveAction`: A function that you call after user press cancel

Expected outcome:

1. Very simple.  Just show "Confirm remove card from ${brand}, card number XXXX ${last4}?" on the screen
2. Below this sentence, show 2 buttons.  "OK", "Cancel"
3. When user press cancel, call props.cancelRemoveAction
4. When user press OK, trigger GraphQL mutation `removeStripeSource`.  If there's no error, call props.onRemoveSuccess

Note:
1. Wrap all visible wordings in a translation function `t`.
2. This "form" will be shown on a Modal.  You can play with this by visiting `http://localhost:3000/editAccount/5b518c4c031c7d0179e23b6a/edit`, (login: 61293993, password: Abc123)
Choose a credit card, press the "Remove Credit Card button", this form is expected to show on there.

**Comment by screw123** [comment]
Sample data for props `source`
```{
    "amount": null,
    "card": {
        "brand": "Visa",
        "exp_month": 11,
        "exp_year": 2022,
        "last4": "4242"
    },
    "client_secret": "src_client_secret_EGb2e2c1b17Gdnt9yD3vRvQI",
    "created": 1546412959,
    "currency": "usd",
    "flow": "receiver",
    "id": "src_1Do3qt2eZvKYlo2CxTH3gRwL",
    "livemode": false,
    "metadata": {},
    "object": "source",
    "statement_descriptor": null,
    "status": "pending",
    "type": "ach_credit_transfer",
    "usage": "reusable"
}

**Comment by screw123** [comment]
@omiq17 A new component.  This is has something brand new to you, namely 1. Wrap and make use of the translation function.  2. Try to call backend using GraphQL.  please try, let me know for anything that is not clear to you, thanks.

**Comment by screw123** [comment]
@omiq17 by the way, please git pull for latest version from github.

**Comment by omiq17** [comment]
Thanks Ross! I will check this out and hope to deliver outcome within Friday.

**Comment by screw123** [comment]
@omiq17 kind reminder.
This will not block development of other parts of the app, you can take your time.

**Comment by omiq17** [comment]
Okay...  Thanks for the information.

**Comment by omiq17** [comment]
Today, I am getting this error while visiting here:  `http://localhost:3000/editAccount/5b518c4c031c7d0179e23b6a/edit`
[Error Image](https://ibb.co/Wx4J3vj)

Can you please check.

**Comment by omiq17** [comment]
Sorry for late. I have created the initial competent. Write demo functions to pass as props on `TestPage.js`.

Check on `RemoveCreditCardForm` branch at `http://localhost:3000/testPage` & let me know the necessary corrections.

**Comment by omiq17** [comment]
I also discovered the basics of `GraphQL`. It seems great to use instead of `REST API`.

**Comment by screw123** [comment]
GraphQL is indeed also REST.  It just put on additional syntax add logic on server side in my opinion.  A Nice concept though.

I will check the code now.  Thanks.

**Comment by omiq17** [comment]
Hmm... Good point.
