### ISSUE TITLE
DateTimePicker

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#66]
I have been reviewing date / datetime picker packages and they are not really good for use, as we need some special feature.

- ability to disable certain days 
- can display custom info for days, e.g. showing Chinese lunar calendar, showing a price for each day within the calendar
- able to style using styled-component

I have started on a DateTime picker on our own.  Please help to make changes on following:

- [x] hide the scrollbars, while keeping the scroll functionality (I think it can be done using CSS?  I briefly tried but unsuccessful, so leave it to you)
- [x] add a prop `selectedDate` to DateTimePicker, and apply a different CSS style to the date selected

- [x] accept a prop `showTimeSlot` and `timeSlot`.
`timeSlot` is expected to be an array of object {display: react component, offset: moment duration}.
When a timeslot is selected, apply offset to selected date
if `showTimeSlot` is true, show timeslot options below the calendar.  You can use `MultiSelect` to display those timeslot

**Comment by screw123** [comment]
Hi Rakib,

I'm now drafting the pick up / delivery functions, then it comes up with the requirement of a datetime picker.  As stated above I think we need to implement our own as none of existing has the flexibility needed.

For the time part, we only need a timeslot for now, so the picker for exact time can be on hold.

Timeslot is like:
[{display: Morning: 9am-1pm, offset: 9 hrs},
{display: Afternoon: 1pm-6pm, offset: 13 hrs},
{display: Night: 6pm-10pm, offset: 18hrs}]

If I am not explaining clearly above, please let me know.  Thanks!

**Comment by screw123** [comment]
@omiq17 also please create a branch from master.

**Comment by omiq17** [comment]
OK... I will work on this and let you know.

**Comment by omiq17** [comment]
Hi, 
I am working on this issue by opening a new branch `DateTimePicker`. Need to clear out some confusions about timeslot:
- Timeslots will be displayed while showTimeSlot is true.
- Suppose, selected date is 2019-01-27 and user click on Morning timeslot, then I will apply it's offset to the selected date like { "2019-01-27", "9 hrs" }. If click on another then apply again  { "2019-01-27", "18 hrs" }. 
- Then, where will I keep this array of objects? Will I take new state to save this. Or, no need to save this for now?

Am I clear to you... Let me know.

**Comment by omiq17** [comment]
I understand the `dayOnClick` function. It sets the date to `selectedDate` state and it is a moment object. I used this state to highlight user selected date.

Now I added a function `setOffset` to apply offset to the `selectedDate`. When a timeslot is selected this function add a field named `offset` to `seletedDate` object. 

I am not properly sure if I did it correctly or not. Check and feel free to give me corrections. Thanks.

**Comment by screw123** [comment]
@omiq17 I made following changes:

1. Some cosmetic changes
2. For offset, what I want to do is to really modify the time portion of the moment object that we return to parent.  Just realized it's not possible without adding state to remember the state of timeslot.  So I made the necessary change just now
3. Changed the timeslot display from dropdown to "radio buttons"

**Comment by screw123** [comment]
@omiq17 now I want to make further modifications as follow:

- [ ] When the component loads, auto scroll to the today row.  E.g. today is 28 Jan, and 28 Jan is current on 5th row of the calendar.  Auto scroll to 5th row on load.

- [ ] We need a header that shows the current selected date.  I think (react-infinite-calendar)[http://clauderic.github.io/react-infinite-calendar]

**Comment by omiq17** [comment]
Seems you add code on this branch. Timeslot looks nice now. Good use of `startOf` function of moment to set offset (Sorry, I didn't get it before).

> I change the padding value a bit to show a minimized scrollbar, it is needed as not everyone have a scroll wheel on mouse. Is there any other way to do it properly? Please advise and change code if needed.

Experimented for a while and finally, got it to auto scroll once when the page loads at first. Check `autoScrollOnce` function. 

> I change the padding value a bit to show a minimized scrollbar, it is needed as not everyone have a scroll wheel on mouse. Is there any other way to do it properly? Please advise and change code if needed.

As you stated to hide the scrollbars at first comment, I hide it by adding this padding. It is also a matter of fact for the users who don't have  wheel on mouse.

In this case, I added event listener for Up and Down Arrow Key and scroll with it. I removed `scroll-behavior: smoth;` here as it doesn't work properly if I hold the Up or Down Key ( in case of continuously scrolling). 

Otherwise, I think we can add two arrow buttons (one at the top, one at the bottom) for scrolling.

These are my opinions on this issue. Choose what you think is good.

I will work with other two issues hopefully on tomorrow. Thanks!

**Comment by screw123** [comment]
@omiq17 
Review the code and this is interesting to scroll on load.  I never thought of this.  So happened a found a way to scroll using a react-virtualized built-in way.  However I keep the autoscroll code for now.  It could be useful for future.

Showing 1/3 of the scrollbar looks a bit hacky, I just afraid some browser does not support this well.  Suggest to hide the scrollbar completely, and add arrow button instead.  Please help to implement.

**Comment by omiq17** [comment]
Taken an empty div and gave it necessary style to hide the scrollbar. Let me know if it is acceptable to you or not. Then I will add two arrow buttons for scrolling.

**Comment by screw123** [comment]
@omiq17 
Using FireFox I can still see the scrollbar
![image](https://user-images.githubusercontent.com/18388411/51971032-3b0d8b00-24b3-11e9-86b3-2711a2d08f57.png)

**Comment by omiq17** [comment]
Nice catch.
I have mistakenly zoomed my browser while coding. I am fixing it.

**Comment by omiq17** [comment]
Pushed a new commit. Please check now. 
One problem remains. If you zoom the browser, the scrollbar gets visible slowly. Is it acceptable?

Also added code to show the month. Check this also.

**Comment by omiq17** [comment]
Check with year, month now.

**Comment by omiq17** [comment]
![header](https://user-images.githubusercontent.com/14343228/51976438-d6e8c800-24ae-11e9-839c-51612b4e0031.png)
Will I consider this section as header and restyle it. Or will I add a new separate header.

**Comment by screw123** [comment]
@omiq17 looks good now, thanks!
Header I prefer something like http://clauderic.github.io/react-infinite-calendar

**Comment by omiq17** [comment]
Welcome, Ross.

Header added. Take a look at it. Required some time to figure out the animation of it. Finally, got a way by copying the header (see `DateHeader` and `DateHeaderCopy`). Suggest if you need to change the design of it.

Added arrow buttons using Font Awesome icons for scrolling (Removed keyboard event handlers).

Please check the proceedings. Thanks!

**Comment by omiq17** [comment]
Sorry for late.
Thanks for your comments.

1,2,3 done.

> Now the animation relies on an additional state in parent, which, I think is quite odd, and it will be better if we can move the date always in same direction instead of back and forth.  (Point 4 is minor at this stage, we can keep it for later if it's too much work)

Moved `toggleHeader` state to its own component. Removed `DateHeaderCopy`. Instead made transition on color and background.

Please check and let me know the corrections.
Thanks.

**Comment by screw123** [comment]
@omiq17 is it a must to make some changes in order to show animations?

I still find it odd to keep changing the header everytime we click a new date.

If that's the case I prefer to remove the animation for now and leave it for later, it is still fine.

Other parts are fine, I can make some final tuning myself.  Thanks.

**Comment by omiq17** [comment]
I thought the animation will catch the eye of user :D

No problem.. Tune yourself and push to this branch.  Then I will pull, remove the animation and let you know. 

Thanks.

**Comment by screw123** [comment]
@omiq17 I have done my part:
1. Made some change to the arrow
2. Change the way the scrollTop is called.  This is necessary as I will have cases that multiple datepicker will be present, this referring by id will not work
3. Made slight change to header presentation + making locale work.

Pls check if I have removed the animation properly.  If yes pls create a pull request and I will merge it with master, thanks.

**Comment by omiq17** [comment]
Actually, I wanted to make an animation like React Infinite Calendar header. But couldn't do it :cry:

You code well. I refactor a bit and created a pull request to master. Thanks.

**Comment by screw123** [comment]
@omiq17 Thanks for confirming.  I will close this and merge with master.
