### ISSUE TITLE
ContainerList

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#69]
In the branch PickUpOrder, you can find a new component `ContainerList`, which is in `./src/component/ContainerList.js`

Sorry I don't have time to separate it out, so pls add a branch from branch PickUpOrder.

This ContainerList is actually a more customized `InfoList`, which you worked on earlier.

The way to call it, you can see from `AddPickUpOrderForm.js`
Sample:
`<ContainerList
    containerList={containers}
    SKUInfo={SKU}
    updateSelected={a=> {
        setFieldValue('containerList', a)
        this.recalcPrice({selected: a, SKU: SKU, priceList: priceList})
    }}
    selected={values['containerList']}
/>`

I already put in some basic structures.
Please help to:

1. Above the `List`, add a `Section` just like other components.
2. In the section, add a line "Number of container selected: (count this.props.selected)"
3. Add a button "Select All", when clicked, call `this.props.updateSelected` with id of all containers in array.
4. Add a button "Remove All", when clicked, call `this.props.updatedSelected` with an empty array
5. Help to make it looks a bit better by modifying CSS. (No need to be super beautiful as there will be more changes to this component later)

Thanks!

**Comment by screw123** [comment]
@omiq17 pls help as above, thanks!

**Comment by omiq17** [comment]
Welcome.

Check the component on `ContainerList` branch. Also check handling functions on line 85.
I have checked the `Section` component (commenting out `List` component) from `TestPage`.

Let me know if you have any comments. Thanks.
