### ISSUE TITLE
ContainerDetails

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#74]
```{
    "_id": "5c516ab49d02c45c7131c942",
    "accountOwner_id": "5b518c4c031c7d0179e23b6a",
    "autoRenew": true,
    "containerType_id": "5b110d2d4e3d922dacfd3ed6",
    "containerTypeName": "Standard Box",
    "containerTypeShortCode": "STANDARD",
    "containerUserInfo_id": [],
    "finishedEvents_id": [
        {
            "createDateTime": "2019-02-15T05:48:50.937Z",
            "docType": "PickUpOrder",
            "eventType": "SHIPTO_WAREHOUSE",
            "msg": "Container scheduled to ship to WiseKeep, at 2019-02-16T09:00:00+08:00, from sfsdfdf sdfdsfdsf dsfsdf KOWLOON .  Attn:ssd.  Tel:54545454",
            "user_id": "5b518c4b031c7d0179e23b69",
            "userName": "Ross Chiu"
        },
        {
            "createDateTime": "2019-02-18T09:48:58.195Z",
            "doc_id": "5c6a7f8889d92c25aa2bc97d",
            "docType": "DeliveryOrder",
            "eventType": "SEND_EMPTY_CONTAINER",
            "msg": "Container scheduled to ship from WiseKeep, at 2019-02-19T09:00:00+08:00, to sfsdfdf sdfdsfdsf dsfsdf KOWLOON .  Attn:ssd.  Tel:54545454",
        }
    ],
    "heightM": 0.31,
    "lengthM": 0.6,
    "paidDuration": 5,
    "paidTerms": "DAY",
    "printId": "WR5F",
    "rentalOrder_id": "5c516aae9d02c45c7131c939",
    "status": "PENDING_INBOUND",
    "storageExpiryDate": "2020-01-01T00:00:00.000Z",
    "storageStartDate": "2019-01-01T00:00:00.000Z",
    "upcomingEvents_id": [],
    "userDefinedName": "haha my box",
    "weightKG": 20,
    "widthM": 0.4
}`

**Comment by screw123** [comment]
@omiq17 
I need a `ContainerDetails` form, which, if provided a `Container` object (example above), will show details of the container.
All fields are finalized except `containerUserInfo_id`, which I will confirm tomorrow when I have time.

Please kindly help to draft the first version of `ContainerDetails`.  It doesn't matter too much if you misinterpret the meaning / importance / data type of the field, but please use your knowledge to guess and think of a way to present them in a good way.

I'm not getting enough time this week to work on this, so I need your help to draft this out, then I will know how to proceed.  Thanks!

**Comment by omiq17** [comment]
Welcome, Ross
I have a confusion here: 
 - Will I make a form with input fields (like `112 Edit Login Info`) and use the `Container` object to set the initial values.
- Or will I make a simple page to show the `Container` details?

Please let me know. Thanks.

**Comment by screw123** [comment]
will I make a simple page to show the `Container` details? <--- this
I'm preparing a page that list all `Containers`.  Once clicked on individual item, I will redirect user to your `ContainerDetails` to show in details what is inside.

**Comment by omiq17** [comment]
Okay, I got it.

**Comment by omiq17** [comment]
Added `ContainerDetailsForm.js` for showing details information. Check [testPage](http://localhost:3000/testPage) of `ContainerDetails` branch. Let me know the corrections.

I am so sorry for late at this time. You can assign me to new issues. I hope to delivery fast next time. Thanks!

**Comment by screw123** [comment]
@
