### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#78]
To style the login screen so it looks like what has designed by @lastresmoya 

@omiq17 I have talked to you separately on this, and I though you already started a branch and working on.  This is just for record purpose.

**Comment by omiq17** [comment]
The initial login screen has done. Try to copy the prototype at most. Though haven't added "Or login with Facebook Google", "Remember me" as these are not available in our app currently.

I have change css styles in many cases with my sense to follow the given prototype. Especially, in `BasicComponent.js`, `FormikForm.js`, `Formik-Basic.js`. I marked as `//comment` to previous styles. You can check changes in these files.

Please check the Login screen in `login` branch and let me know your comment. Thanks!

**Comment by omiq17** [comment]
The title and button `font-weight` I am getting from invision app is 500. But I think it should be 600. Please check this at `LoginPageStyles.js`

**Comment by screw123** [comment]
Initial look it's all very good!  Will review + merge into master today.
